### ISSUE TITLE
It's not able to open pdf file after downloading it

### ISSUE THREAD

**Issue by emilylai84** [Xvier/cypress-downloadfile#13] opened 2020-04-27 15:29 UTC
It's not able to open pdf file after downloading it
I use below command for downloading 'test.pdf' file to 'download' folder.
cy.downloadFile('apiURL', 'download', 'test.pdf');

Steps
It's able to download that pdf file to "download" folder in cypress. However, it's not able to open it 

`Adobe Acrobat Reader could not open 'test.pdf' because it is either not a supported file type or because the file has been damaged (for example, it was sent as an email attachment and wasn't correctly decoded).`

Note: 
- paste that link to browser, able to download and open the file properly.
- works with excel and word files

Expected result:
It should be able to download and open any file type.

**Comment by Xvier** [comment] 2020-04-29 10:16
@emilylai84  Do you have more info for me

- What version of cypress are you using
- What is the link you are using to download the pdf



This is an example pdf i downloaded with this command so for me downloading pdf's work. So maybe your link is incorrect or the download is maybe cancelled on your side?

describe('Downloading a pdf', () => {
    it('Pdf download', () => {
        cy.downloadFile('http://www.pdf995.com/samples/pdf.pdf','downloads','my.pdf');
    });
});


![image](https://user-images.githubusercontent.com/16205119/80585950-75e2d380-8a14-11ea-9867-417042f9ce35.png)

**Comment by emilylai84** [comment] 2020-05-04 07:57
**What version of cypress are you using**
"cypress": "^4.4.1"

**What is the link you are using to download the pdf**
It's not a direct link like that, it's a generated link as below. The link is correct, as I am able to download word, excel file with the same way.

"domain/Download.asp?FileID=id&IsAdobePluginEnabled=false&IsChromePdfViewerEnabled=true&WillUseAdobePlugin=false&Os=MacIntel&DownloadCode=code&TriggerDownload=true"

**Comment by Xvier** [comment] 2020-05-04 15:06
@emilylai84 since i cannot get the real link it makes it hard for me to find out what is going wrong.
So i will ask some more questions, if you download this manual you get a correct file? And what is the size of the correct file and is it the same size when downloaded with my plugin.

**Comment by emilylai84** [comment] 2020-05-05 08:27
I can't send you the real link because it's required login to get the file. If I have a session (logged in to my system), then paste that link on browser and enter, it's able to download the PDF file properly. 

The downloaded file via your plugin is 3kb, while the correct file is 307kb.

**Downloaded manually via browser (working)**
[02 pdf-non-secured (1).pdf](https://github.com/Xvier/cypress-downloadfile/files/4579649/02.pdf-non-secured.1.pdf)

**Downloaded by plugin (broken)**
[02 pdf-non-secured.pdf](https://github.com/Xvier/cypress-downloadfile/files/4579653/02.pdf-non-secured.pdf)

**Comment by Xvier** [comment] 2020-05-06 12:02
@emilylai84 I think its something with the generated link + pdf combination but i cannot be sure if there is not a way for me to reproduce what you are facing.

i found the pdf via a public link [onlinepdf](https://support.sas.com/resources/papers/proceedings/pdfs/sgf2008/173-2008.pdf)

And i could download this one perfect with the plugin it has the same size 307. So i dont know how to fix your problem.

**Comment by nikhilesh009** [comment] 2020-05-11 15:50
i was trying to play around - in case of _URL + generated link_ . i am trying to concatenate both but when i tried to use cy.downloadFile(newURL) its throwing error. and giving an object 
![Screenshot 2020-05-11 at 17 49 04](https://user-images.githubusercontent.com/40767850/81581985-c57bb480-93af-11ea-97ee-4a9c4d0074d3.png)
![Screenshot 2020-05-11 at 17 40 05](https://user-images.githubusercontent.com/40767850/81582024-d2000d00-93af-11ea-9f69-8e732e7e939d.png)

**Comment by Xvier** [comment] 2020-05-12 17:43
@nikhilesh009 is this part of this issue, if not please create a new issue with more info like pieces of code. 

But before you do that please check what you concatenated with `typeof(newURL)` so you can check if you pass a string.

**Comment by Xvier** [comment] 2020-07-08 20:27
I will close this issue since I don't get any response. If you still have problems reopen the ticket

**Closed as completed by Xvier** 2020-07-08 20:27 UTC
Labels: question
